*==============================================================================
* PANEL DATA ANALYSIS: LOG TRANSFORMATIONS, FE, RE & HAUSMAN TEST
* Variables: mepi npi geff pop popd rpop upop co2pc co2ch fwpc altnuc gdpg ffuel
*
* NOTE (updated): the driver set changed from an earlier draft. Fixing a
* leakage bug in the Python pipeline (Recursive Feature Elimination was
* previously fit on the FULL sample, including the held-out test set) changed
* which variables RFE selects. GDP, PEMD (particulate emission damage) and
* EUPC (energy use per capita) are no longer in the final set; NPI (net
* primary income), UPOP (urban population share) and FWPC (renewable
* internal freshwater resources per capita) are now included instead. See
* data/processed/stata_panel_data.csv / rfe_results.csv (regenerated by
* notebooks/02_modelling_and_interpretation.ipynb) for the source of this
* variable set.
*
* This version also adds, per reviewer request:
*   - Two-way (country + year) fixed effects as a primary specification
*   - A cross-sectional dependence test (Pesaran CD)
*   - Driscoll-Kraay standard errors as an alternative to clustered SEs
*   - A fractional response model (Papke & Wooldridge) as a bounded-outcome
*     alternative to linear FE/RE, since MEPI in [0,1]
*==============================================================================

*------------------------------------------------------------------------------
* SECTION 1: SETUP
*------------------------------------------------------------------------------

clear all
set more off
capture log close

*--- Force a known working directory, regardless of where Stata's cwd was ---
* when this do-file was launched from (e.g. running "do" from a shortcut whose
* working directory is elsewhere, such as Desktop\Stata18\, previously caused
* "file ../data/processed/panel_data.dta not found"). Everything below is then
* relative to stata/, matching the project layout.
cd "C:\Users\GRACE TECH\Desktop\energy_poverty_africa\stata"

log using "panel_analysis.log", replace text

*--- Optional user-written packages needed for Sections 8, 8b and 9 ---
* If not already installed, uncomment the next three lines (needs internet):
* ssc install xtserial, replace
* ssc install xtcsd, replace
* ssc install xtscc, replace

*--- LOAD YOUR DATA FIRST ---
* Path is relative to this .do file's location (stata/panel_analysis.do)
use "../data/processed/panel_data.dta", clear

*--- Set panel structure (adjust countryname and time to your id/time vars) ---
encode countryname, gen(country_id)       // convert string country to numeric
xtset country_id time, yearly             // declare panel; change yearly if needed


*------------------------------------------------------------------------------
* SECTION 2: LOG TRANSFORMATIONS
*------------------------------------------------------------------------------

*--- Standard log (strictly positive variables) ---
foreach var in pop co2pc popd fwpc {
    gen ln_`var' = ln(`var')
    label variable ln_`var' "Log of `var'"
}

*--- Log(x+1) for variables with zeros ---
foreach var in altnuc ffuel {
    gen ln_`var' = ln(`var' + 1)
    label variable ln_`var' "Log(1 + `var')"
}

*--- Inverse hyperbolic sine for variables containing negative values ---
* co2ch: CO2 emissions % change from 1990 -- can be negative
* npi  : net primary income (BoP) -- frequently negative for net-debtor economies
foreach var in co2ch npi {
    gen ihs_`var' = asinh(`var')
    label variable ihs_`var' "IHS transformation of `var'"
}

*--- Leave untransformed: mepi, geff, rpop, upop, gdpg ---
* rpop and upop are already bounded percentages of total population;
* geff and gdpg are already on a small, roughly symmetric scale.

*--- Confirm transformations reduced skewness (upop kept here for reference; ---
*    see note in Section 3 on why it is dropped from the regression itself) ---
summarize ln_pop ln_co2pc ln_popd ln_fwpc ///
          ln_altnuc ln_ffuel ihs_co2ch ihs_npi mepi geff rpop upop gdpg, detail


*------------------------------------------------------------------------------
* SECTION 3: DEFINE DEPENDENT AND INDEPENDENT VARIABLES
*
*   Dependent variable : mepi (MPI index — bounded [0,1], near-symmetric)
*   Independent vars   : logged/transformed versions + untransformed controls
*   Adjust this list to match your theoretical model
*------------------------------------------------------------------------------

global depvar  mepi

* NOTE: upop (urban population %) is deliberately excluded here even though
* it is one of the 12 RFE-selected drivers. rpop + upop = 100 exactly (they
* are complementary shares of total population), so once rpop is in the
* model upop is perfectly collinear with it (and with the constant/FE) and
* carries no additional linear information -- Stata auto-drops it from every
* xtreg specification regardless ("note: upop omitted because of
* collinearity"), so including it in this list only added clutter. This is
* not an issue for the Python tree-based models (Random Forest, Gradient
* Boosting, XGBoost), which can still register separate importance for both
* via non-linear splits even though the two are linearly dependent.
global indvars ihs_npi geff ln_pop ln_popd rpop ///
               ln_co2pc ihs_co2ch ln_fwpc ln_altnuc gdpg ln_ffuel


*------------------------------------------------------------------------------
* SECTION 4: DESCRIPTIVE CHECK ON PANEL STRUCTURE
*------------------------------------------------------------------------------

xtsum $depvar $indvars
xtline mepi, overlay legend(off) title("MEPI over time by country")


*------------------------------------------------------------------------------
* SECTION 5: FIXED EFFECTS (FE) ESTIMATION — country FE (one-way, baseline)
*   - Absorbs all time-invariant country heterogeneity
*   - Use vce(robust) for heteroskedasticity-robust SEs
*------------------------------------------------------------------------------

xtreg $depvar $indvars, fe vce(robust)
estimates store fe_model

*--- Save FE residuals for diagnostics ---
predict resid_fe, e
predict yhat_fe,  xb


*------------------------------------------------------------------------------
* SECTION 5b: TWO-WAY FIXED EFFECTS (country + year)
*   - Reviewer concern: the original specification had country FE only.
*   - Year dummies absorb continent-wide shocks common to all countries in a
*     given year (e.g. global oil price swings, global financial crises)
*     that would otherwise be attributed to the other regressors.
*------------------------------------------------------------------------------

xtreg $depvar $indvars i.time, fe vce(robust)
estimates store fe_twoway

*--- Joint significance of year effects (also reported standalone in 8) ---
testparm i.time
display "If p < 0.05, year fixed effects are jointly significant -> two-way FE preferred over one-way FE"


*------------------------------------------------------------------------------
* SECTION 6: RANDOM EFFECTS (RE) ESTIMATION
*   - Assumes country effects are uncorrelated with regressors
*   - More efficient than FE if assumption holds
*------------------------------------------------------------------------------

xtreg $depvar $indvars, re vce(robust)
estimates store re_model


*------------------------------------------------------------------------------
* SECTION 7: HAUSMAN TEST
*   - H0: RE is consistent (country effects uncorrelated with regressors)
*   - H1: FE is consistent, RE is not
*   - If p < 0.05 → reject H0 → use Fixed Effects
*   - If p > 0.05 → fail to reject H0 → Random Effects preferred
*
*   NOTE: hausman requires non-robust estimates for the standard test.
*         We re-estimate without vce(robust) solely for the Hausman test.
*------------------------------------------------------------------------------

quietly xtreg $depvar $indvars, fe
estimates store fe_hausman

quietly xtreg $depvar $indvars, re
estimates store re_hausman

hausman fe_hausman re_hausman, sigmamore

*--- Display interpretation reminder ---
display ""
display "  HAUSMAN TEST INTERPRETATION:"
display "  p < 0.05 → Reject H0 → Use FIXED EFFECTS"
display "  p > 0.05 → Fail to reject H0 → RANDOM EFFECTS preferred"
display ""


*------------------------------------------------------------------------------
* SECTION 8: ADDITIONAL DIAGNOSTICS
*------------------------------------------------------------------------------

*--- Test for time fixed effects (add time dummies to FE model) ---
quietly xtreg $depvar $indvars i.time, fe vce(robust)
testparm i.time
display "If p < 0.05, time fixed effects are jointly significant → include them"

*--- Breusch-Pagan LM test: random effects vs pooled OLS ---
xtreg $depvar $indvars, re
xttest0

*--- Modified Wald test for groupwise heteroskedasticity in FE residuals ---
xtreg $depvar $indvars, fe
xttest3

*--- Wooldridge test for serial autocorrelation in panel data ---
capture which xtserial
if _rc {
    display as error "xtserial not installed — run: ssc install xtserial"
}
else {
    xtserial $depvar $indvars
}


*------------------------------------------------------------------------------
* SECTION 8b: CROSS-SECTIONAL DEPENDENCE AND DRISCOLL-KRAAY SEs
*   - Reviewer concern: with N=54 countries and T=23 years, common shocks
*     (e.g. global energy prices, global financial crises) can induce
*     cross-sectional dependence in the residuals that ordinary clustered
*     (by country) SEs do not account for.
*   - Requires the user-written xtcsd and xtscc packages (see Section 1).
*------------------------------------------------------------------------------

capture which xtcsd
if _rc {
    display as error "xtcsd not installed — run: ssc install xtcsd"
}
else {
    quietly xtreg $depvar $indvars, fe
    xtcsd, pesaran abs
    display "Pesaran CD test H0: residuals are cross-sectionally independent."
    display "If p < 0.05, cross-sectional dependence is present -> Driscoll-Kraay SEs (below) are preferred to clustered SEs."
}

capture which xtscc
if _rc {
    display as error "xtscc not installed — run: ssc install xtscc"
}
else {
    *--- Driscoll-Kraay SEs, robust to cross-sectional dependence, heteroskedasticity
    *    and autocorrelation up to the specified lag (default lag chosen by xtscc) ---
    xtscc $depvar $indvars, fe
    estimates store fe_driscoll_kraay

    xtscc $depvar $indvars i.time, fe
    estimates store fe_twoway_driscoll_kraay
}


*------------------------------------------------------------------------------
* SECTION 9: COEFFICIENT TABLE COMPARISON
*------------------------------------------------------------------------------

*--- Side-by-side comparison of one-way FE, two-way FE and RE coefficients ---
estimates table fe_model fe_twoway re_model, ///
    b(%9.4f) se(%9.4f) stats(N r2_w r2_b r2_o) ///
    title("One-way FE vs Two-way FE vs Random Effects — Coefficient Comparison")

capture estimates table fe_model fe_driscoll_kraay, ///
    b(%9.4f) se(%9.4f) stats(N) ///
    title("Country-clustered FE vs Driscoll-Kraay FE — same coefficients, SEs may differ under cross-sectional dependence")


*------------------------------------------------------------------------------
* SECTION 10: FRACTIONAL RESPONSE MODEL (bounded-outcome alternative)
*   - Reviewer suggestion: MEPI in [0,1] makes a fractional response model
*     (Papke & Wooldridge, 1996) a natural alternative to linear FE/RE, which
*     can in principle predict outside [0,1] and does not respect the
*     boundedness of the outcome.
*   - fracreg logit is a pooled (not FE) estimator; country_id is included as
*     a categorical control here as a practical approximation to unobserved
*     heterogeneity. Interpret coefficients as their effect on the logit of
*     E[mepi | X], not as marginal effects — use margins for those.
*------------------------------------------------------------------------------

fracreg logit $depvar $indvars i.country_id, vce(cluster country_id)
estimates store frac_response

display ""
display "Average marginal effects from the fractional response model:"
margins, dydx($indvars) post
estimates store frac_response_margins


*------------------------------------------------------------------------------
* CLOSE LOG
*------------------------------------------------------------------------------

log close
*==============================================================================
* END OF DO FILE
*==============================================================================
